// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

type Querier interface {
	CreateFollower(ctx context.Context, arg CreateFollowerParams) (Follower, error)
	CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationQueue, error)
	CreateNotificationState(ctx context.Context, state State) (NotificationState, error)
	CreateUser(ctx context.Context, username string) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetFollowersByUserID(ctx context.Context, id uuid.UUID) ([]GetFollowersByUserIDRow, error)
	GetUsers(ctx context.Context) ([]User, error)
	ListSendableNotifications(ctx context.Context) ([]ListSendableNotificationsRow, error)
	UpdateNotificationStateByID(ctx context.Context, arg UpdateNotificationStateByIDParams) error
}

var _ Querier = (*Queries)(nil)
