// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: notification.proto

package rpcs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationService_EnqueueNotification_FullMethodName = "/rpcs.NotificationService/EnqueueNotification"
	NotificationService_StreamNotifications_FullMethodName = "/rpcs.NotificationService/StreamNotifications"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	EnqueueNotification(ctx context.Context, in *EnqueueNotificationRequest, opts ...grpc.CallOption) (*EnqueueNotificationResponse, error)
	StreamNotifications(ctx context.Context, opts ...grpc.CallOption) (NotificationService_StreamNotificationsClient, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) EnqueueNotification(ctx context.Context, in *EnqueueNotificationRequest, opts ...grpc.CallOption) (*EnqueueNotificationResponse, error) {
	out := new(EnqueueNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_EnqueueNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) StreamNotifications(ctx context.Context, opts ...grpc.CallOption) (NotificationService_StreamNotificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotificationService_ServiceDesc.Streams[0], NotificationService_StreamNotifications_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationServiceStreamNotificationsClient{stream}
	return x, nil
}

type NotificationService_StreamNotificationsClient interface {
	Send(*StreamNotificationsRequest) error
	Recv() (*StreamNotificationsResponse, error)
	grpc.ClientStream
}

type notificationServiceStreamNotificationsClient struct {
	grpc.ClientStream
}

func (x *notificationServiceStreamNotificationsClient) Send(m *StreamNotificationsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notificationServiceStreamNotificationsClient) Recv() (*StreamNotificationsResponse, error) {
	m := new(StreamNotificationsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	EnqueueNotification(context.Context, *EnqueueNotificationRequest) (*EnqueueNotificationResponse, error)
	StreamNotifications(NotificationService_StreamNotificationsServer) error
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) EnqueueNotification(context.Context, *EnqueueNotificationRequest) (*EnqueueNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueNotification not implemented")
}
func (UnimplementedNotificationServiceServer) StreamNotifications(NotificationService_StreamNotificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_EnqueueNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).EnqueueNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_EnqueueNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).EnqueueNotification(ctx, req.(*EnqueueNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_StreamNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotificationServiceServer).StreamNotifications(&notificationServiceStreamNotificationsServer{stream})
}

type NotificationService_StreamNotificationsServer interface {
	Send(*StreamNotificationsResponse) error
	Recv() (*StreamNotificationsRequest, error)
	grpc.ServerStream
}

type notificationServiceStreamNotificationsServer struct {
	grpc.ServerStream
}

func (x *notificationServiceStreamNotificationsServer) Send(m *StreamNotificationsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notificationServiceStreamNotificationsServer) Recv() (*StreamNotificationsRequest, error) {
	m := new(StreamNotificationsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcs.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueNotification",
			Handler:    _NotificationService_EnqueueNotification_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNotifications",
			Handler:       _NotificationService_StreamNotifications_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "notification.proto",
}
